/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ICloneNursesInterface extends ethers.utils.Interface {
  functions: {
    "approve(address,uint256)": FunctionFragment;
    "assemble(uint256)": FunctionFragment;
    "assembleWithPermit(uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "changeSupportedPower(address,int256)": FunctionFragment;
    "checkSupportingRoute(address)": FunctionFragment;
    "claim(uint256)": FunctionFragment;
    "destroy(uint256,uint256)": FunctionFragment;
    "getApproved(uint256)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "maidCoin()": FunctionFragment;
    "name()": FunctionFragment;
    "nursePart()": FunctionFragment;
    "nurseTypeCount()": FunctionFragment;
    "nurseTypes(uint256)": FunctionFragment;
    "nurses(uint256)": FunctionFragment;
    "ownerOf(uint256)": FunctionFragment;
    "pendingReward(uint256)": FunctionFragment;
    "safeTransferFrom(address,address,uint256)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "setSupportingTo(address,uint256,uint256)": FunctionFragment;
    "shareRewards(uint256,address,uint8)": FunctionFragment;
    "supportedPower(uint256)": FunctionFragment;
    "supportingRoute(uint256)": FunctionFragment;
    "supportingTo(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "theMaster()": FunctionFragment;
    "tokenByIndex(uint256)": FunctionFragment;
    "tokenOfOwnerByIndex(address,uint256)": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
    "totalRewardsFromSupporters(uint256)": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assemble",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assembleWithPermit",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "changeSupportedPower",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSupportingRoute",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "destroy",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "maidCoin", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "nursePart", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nurseTypeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nurseTypes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nurses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupportingTo",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shareRewards",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedPower",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportingRoute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportingTo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "theMaster", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRewardsFromSupporters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assemble", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assembleWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeSupportedPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSupportingRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "destroy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maidCoin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nursePart", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nurseTypeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nurseTypes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nurses", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupportingTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shareRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportingRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportingTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "theMaster", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardsFromSupporters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "ChangeSupportedPower(uint256,int256)": EventFragment;
    "ChangeSupportingRoute(uint256,uint256)": EventFragment;
    "Claim(uint256,address,uint256)": EventFragment;
    "SupportTo(address,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "TransferSupportingRewards(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChangeSupportedPower"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChangeSupportingRoute"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SupportTo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferSupportingRewards"): EventFragment;
}

export class ICloneNurses extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ICloneNursesInterface;

  functions: {
    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    assemble(
      nurseType: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "assemble(uint256)"(
      nurseType: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    assembleWithPermit(
      nurseType: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "assembleWithPermit(uint256,uint256,uint8,bytes32,bytes32)"(
      nurseType: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    changeSupportedPower(
      supporter: string,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeSupportedPower(address,int256)"(
      supporter: string,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkSupportingRoute(
      supporter: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkSupportingRoute(address)"(
      supporter: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claim(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claim(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    destroy(
      id: BigNumberish,
      toId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "destroy(uint256,uint256)"(
      id: BigNumberish,
      toId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { operator: string }>;

    "getApproved(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { operator: string }>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isApprovedForAll(address,address)"(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    maidCoin(overrides?: CallOverrides): Promise<[string]>;

    "maidCoin()"(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    "name()"(overrides?: CallOverrides): Promise<[string]>;

    nursePart(overrides?: CallOverrides): Promise<[string]>;

    "nursePart()"(overrides?: CallOverrides): Promise<[string]>;

    nurseTypeCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "nurseTypeCount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    nurseTypes(
      typeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        partCount: BigNumber;
        destroyReturn: BigNumber;
        power: BigNumber;
      }
    >;

    "nurseTypes(uint256)"(
      typeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        partCount: BigNumber;
        destroyReturn: BigNumber;
        power: BigNumber;
      }
    >;

    nurses(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { nurseType: BigNumber }>;

    "nurses(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { nurseType: BigNumber }>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { owner: string }>;

    "ownerOf(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { owner: string }>;

    pendingReward(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "pendingReward(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      operator: string,
      _approved: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setApprovalForAll(address,bool)"(
      operator: string,
      _approved: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setSupportingTo(
      supporter: string,
      to: BigNumberish,
      amounts: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setSupportingTo(address,uint256,uint256)"(
      supporter: string,
      to: BigNumberish,
      amounts: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    shareRewards(
      pending: BigNumberish,
      supporter: string,
      supportingRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "shareRewards(uint256,address,uint8)"(
      pending: BigNumberish,
      supporter: string,
      supportingRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    supportedPower(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "supportedPower(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    supportingRoute(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "supportingRoute(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    supportingTo(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "supportingTo(address)"(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    "symbol()"(overrides?: CallOverrides): Promise<[string]>;

    theMaster(overrides?: CallOverrides): Promise<[string]>;

    "theMaster()"(overrides?: CallOverrides): Promise<[string]>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "tokenByIndex(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { tokenId: BigNumber }>;

    "tokenOfOwnerByIndex(address,uint256)"(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { tokenId: BigNumber }>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    totalRewardsFromSupporters(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "totalRewardsFromSupporters(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalSupply()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  approve(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  assemble(
    nurseType: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "assemble(uint256)"(
    nurseType: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  assembleWithPermit(
    nurseType: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "assembleWithPermit(uint256,uint256,uint8,bytes32,bytes32)"(
    nurseType: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  changeSupportedPower(
    supporter: string,
    power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeSupportedPower(address,int256)"(
    supporter: string,
    power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkSupportingRoute(
    supporter: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkSupportingRoute(address)"(
    supporter: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claim(id: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>;

  "claim(uint256)"(
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  destroy(
    id: BigNumberish,
    toId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "destroy(uint256,uint256)"(
    id: BigNumberish,
    toId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getApproved(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getApproved(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  isApprovedForAll(
    owner: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isApprovedForAll(address,address)"(
    owner: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  maidCoin(overrides?: CallOverrides): Promise<string>;

  "maidCoin()"(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  nursePart(overrides?: CallOverrides): Promise<string>;

  "nursePart()"(overrides?: CallOverrides): Promise<string>;

  nurseTypeCount(overrides?: CallOverrides): Promise<BigNumber>;

  "nurseTypeCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  nurseTypes(
    typeId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      partCount: BigNumber;
      destroyReturn: BigNumber;
      power: BigNumber;
    }
  >;

  "nurseTypes(uint256)"(
    typeId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      partCount: BigNumber;
      destroyReturn: BigNumber;
      power: BigNumber;
    }
  >;

  nurses(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "nurses(uint256)"(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "ownerOf(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  pendingReward(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "pendingReward(uint256)"(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "safeTransferFrom(address,address,uint256)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256,bytes)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    operator: string,
    _approved: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setApprovalForAll(address,bool)"(
    operator: string,
    _approved: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setSupportingTo(
    supporter: string,
    to: BigNumberish,
    amounts: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setSupportingTo(address,uint256,uint256)"(
    supporter: string,
    to: BigNumberish,
    amounts: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  shareRewards(
    pending: BigNumberish,
    supporter: string,
    supportingRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "shareRewards(uint256,address,uint8)"(
    pending: BigNumberish,
    supporter: string,
    supportingRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  supportedPower(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "supportedPower(uint256)"(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  supportingRoute(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "supportingRoute(uint256)"(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  supportingTo(
    supporter: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "supportingTo(address)"(
    supporter: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  "symbol()"(overrides?: CallOverrides): Promise<string>;

  theMaster(overrides?: CallOverrides): Promise<string>;

  "theMaster()"(overrides?: CallOverrides): Promise<string>;

  tokenByIndex(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "tokenByIndex(uint256)"(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenOfOwnerByIndex(
    owner: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "tokenOfOwnerByIndex(address,uint256)"(
    owner: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "tokenURI(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  totalRewardsFromSupporters(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "totalRewardsFromSupporters(uint256)"(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  transferFrom(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "approve(address,uint256)"(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    assemble(nurseType: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "assemble(uint256)"(
      nurseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    assembleWithPermit(
      nurseType: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "assembleWithPermit(uint256,uint256,uint8,bytes32,bytes32)"(
      nurseType: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeSupportedPower(
      supporter: string,
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeSupportedPower(address,int256)"(
      supporter: string,
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkSupportingRoute(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;

    "checkSupportingRoute(address)"(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;

    claim(id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "claim(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    destroy(
      id: BigNumberish,
      toId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "destroy(uint256,uint256)"(
      id: BigNumberish,
      toId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getApproved(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isApprovedForAll(address,address)"(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    maidCoin(overrides?: CallOverrides): Promise<string>;

    "maidCoin()"(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;

    nursePart(overrides?: CallOverrides): Promise<string>;

    "nursePart()"(overrides?: CallOverrides): Promise<string>;

    nurseTypeCount(overrides?: CallOverrides): Promise<BigNumber>;

    "nurseTypeCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    nurseTypes(
      typeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        partCount: BigNumber;
        destroyReturn: BigNumber;
        power: BigNumber;
      }
    >;

    "nurseTypes(uint256)"(
      typeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        partCount: BigNumber;
        destroyReturn: BigNumber;
        power: BigNumber;
      }
    >;

    nurses(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "nurses(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "ownerOf(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    pendingReward(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pendingReward(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      operator: string,
      _approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setApprovalForAll(address,bool)"(
      operator: string,
      _approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setSupportingTo(
      supporter: string,
      to: BigNumberish,
      amounts: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setSupportingTo(address,uint256,uint256)"(
      supporter: string,
      to: BigNumberish,
      amounts: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    shareRewards(
      pending: BigNumberish,
      supporter: string,
      supportingRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & {
        nurseOwner: string;
        amountToNurseOwner: BigNumber;
      }
    >;

    "shareRewards(uint256,address,uint8)"(
      pending: BigNumberish,
      supporter: string,
      supportingRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & {
        nurseOwner: string;
        amountToNurseOwner: BigNumber;
      }
    >;

    supportedPower(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportedPower(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportingRoute(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportingRoute(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportingTo(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportingTo(address)"(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    "symbol()"(overrides?: CallOverrides): Promise<string>;

    theMaster(overrides?: CallOverrides): Promise<string>;

    "theMaster()"(overrides?: CallOverrides): Promise<string>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenByIndex(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenOfOwnerByIndex(address,uint256)"(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    totalRewardsFromSupporters(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "totalRewardsFromSupporters(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Approval(
      owner: string | null,
      approved: string | null,
      tokenId: BigNumberish | null
    ): EventFilter;

    ApprovalForAll(
      owner: string | null,
      operator: string | null,
      approved: null
    ): EventFilter;

    ChangeSupportedPower(id: BigNumberish | null, power: null): EventFilter;

    ChangeSupportingRoute(
      from: BigNumberish | null,
      to: BigNumberish | null
    ): EventFilter;

    Claim(
      id: BigNumberish | null,
      claimer: string | null,
      reward: null
    ): EventFilter;

    SupportTo(supporter: string | null, to: BigNumberish | null): EventFilter;

    Transfer(
      from: string | null,
      to: string | null,
      tokenId: BigNumberish | null
    ): EventFilter;

    TransferSupportingRewards(
      supporter: string | null,
      id: BigNumberish | null,
      amounts: null
    ): EventFilter;
  };

  estimateGas: {
    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    assemble(
      nurseType: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "assemble(uint256)"(
      nurseType: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    assembleWithPermit(
      nurseType: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "assembleWithPermit(uint256,uint256,uint8,bytes32,bytes32)"(
      nurseType: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeSupportedPower(
      supporter: string,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeSupportedPower(address,int256)"(
      supporter: string,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    checkSupportingRoute(
      supporter: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "checkSupportingRoute(address)"(
      supporter: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    claim(id: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "claim(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    destroy(
      id: BigNumberish,
      toId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "destroy(uint256,uint256)"(
      id: BigNumberish,
      toId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getApproved(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isApprovedForAll(address,address)"(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maidCoin(overrides?: CallOverrides): Promise<BigNumber>;

    "maidCoin()"(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;

    nursePart(overrides?: CallOverrides): Promise<BigNumber>;

    "nursePart()"(overrides?: CallOverrides): Promise<BigNumber>;

    nurseTypeCount(overrides?: CallOverrides): Promise<BigNumber>;

    "nurseTypeCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    nurseTypes(
      typeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "nurseTypes(uint256)"(
      typeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nurses(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "nurses(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ownerOf(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingReward(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pendingReward(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: string,
      _approved: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setApprovalForAll(address,bool)"(
      operator: string,
      _approved: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setSupportingTo(
      supporter: string,
      to: BigNumberish,
      amounts: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setSupportingTo(address,uint256,uint256)"(
      supporter: string,
      to: BigNumberish,
      amounts: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    shareRewards(
      pending: BigNumberish,
      supporter: string,
      supportingRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "shareRewards(uint256,address,uint8)"(
      pending: BigNumberish,
      supporter: string,
      supportingRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    supportedPower(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportedPower(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportingRoute(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportingRoute(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportingTo(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportingTo(address)"(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    "symbol()"(overrides?: CallOverrides): Promise<BigNumber>;

    theMaster(overrides?: CallOverrides): Promise<BigNumber>;

    "theMaster()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenByIndex(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenOfOwnerByIndex(address,uint256)"(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalRewardsFromSupporters(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "totalRewardsFromSupporters(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approve(address,uint256)"(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    assemble(
      nurseType: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "assemble(uint256)"(
      nurseType: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    assembleWithPermit(
      nurseType: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "assembleWithPermit(uint256,uint256,uint8,bytes32,bytes32)"(
      nurseType: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    changeSupportedPower(
      supporter: string,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeSupportedPower(address,int256)"(
      supporter: string,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkSupportingRoute(
      supporter: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkSupportingRoute(address)"(
      supporter: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claim(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claim(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    destroy(
      id: BigNumberish,
      toId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "destroy(uint256,uint256)"(
      id: BigNumberish,
      toId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getApproved(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isApprovedForAll(address,address)"(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maidCoin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maidCoin()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nursePart(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "nursePart()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nurseTypeCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "nurseTypeCount()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nurseTypes(
      typeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nurseTypes(uint256)"(
      typeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nurses(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nurses(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ownerOf(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingReward(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pendingReward(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: string,
      _approved: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setApprovalForAll(address,bool)"(
      operator: string,
      _approved: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setSupportingTo(
      supporter: string,
      to: BigNumberish,
      amounts: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setSupportingTo(address,uint256,uint256)"(
      supporter: string,
      to: BigNumberish,
      amounts: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    shareRewards(
      pending: BigNumberish,
      supporter: string,
      supportingRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "shareRewards(uint256,address,uint8)"(
      pending: BigNumberish,
      supporter: string,
      supportingRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    supportedPower(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportedPower(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportingRoute(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportingRoute(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportingTo(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportingTo(address)"(
      supporter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "symbol()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    theMaster(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "theMaster()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenByIndex(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenOfOwnerByIndex(address,uint256)"(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalRewardsFromSupporters(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "totalRewardsFromSupporters(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalSupply()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
