/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILingerieGirls,
  ILingerieGirlsInterface,
} from "../ILingerieGirls";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "lingerieGirls",
    outputs: [
      {
        internalType: "uint256",
        name: "originPower",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "supportedLPTokenAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sushiRewardDebt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILingerieGirls__factory {
  static readonly abi = _abi;
  static createInterface(): ILingerieGirlsInterface {
    return new utils.Interface(_abi) as ILingerieGirlsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILingerieGirls {
    return new Contract(address, _abi, signerOrProvider) as ILingerieGirls;
  }
}
